# Generated by Django 2.0.6 on 2019-05-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_confirm_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
        migrations.AlterField(
            model_name='confirm_string',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.TUser'),
        ),
    ]
